### ISSUE TITLE
OperationalError: no such table: tag

### ISSUE THREAD

**Issue by brianjmurrell** [MediaBrowser/plugin.video.emby#102]
I'm getting the following error trying to do a manual sync:

```
16:40:11.983 T:2698992448  NOTICE: EMBY.views -> creating view Movies: f137a2dd21bbc1b99aa5c0f6bf02a805
16:40:11.996 T:2698992448  NOTICE: EMBY.database -> ERROR:: Type: <class 'sqlite3.OperationalError'> Value: no such table: tag
16:40:11.997 T:2698992448  NOTICE: EMBY.database -> closing: /home/mythtv/.kodi/userdata/Database/MyVideos107.db - 2846530920
16:40:11.999 T:2698992448  NOTICE: EMBY.database -> ERROR:: Type: <class 'sqlite3.OperationalError'> Value: no such table: tag
16:40:12.000 T:2698992448  NOTICE: EMBY.database -> closing: /home/mythtv/.kodi/userdata/Database/emby.db - 2739211216
16:40:12.166 T:2749348672   DEBUG: Caching image 'http://mirrors.kodi.tv/addons/krypton/plugin.video.cnet.podcasts/icon.png' to 'b/b8accd3a.jpg':
16:40:12.166 T:2749348672   DEBUG: cached image 'special://masterprofile/Thumbnails/b/b8accd3a.jpg' size 256x256
16:40:12.492 T:2749348672   DEBUG: Using proxy proxy, type 0
16:40:12.527 T:2429795136  NOTICE: EMBY.ga_client -> ERROR:: hostname 'www.google-analytics.com' doesn't match either of '*.urlfilterdb.com', 'urlfilterdb.com'
16:40:12.530 T:2429795136  NOTICE: EMBY.librarysync -> ERROR:: no such table: tag
                                            Traceback (most recent call last):
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 621, in run
                                                self.run_internal()
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 716, in run_internal
                                                librarySync = self.startSync()
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 112, in startSync
                                                completed = self.fullSync()
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 283, in fullSync
                                                views.Views(cursor_emby, cursor_video).maintain()
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/views.py", line 107, in maintain
                                                if self.compare_view(media_type, view_id, view_name, view_type):
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/views.py", line 172, in compare_view
                                                self.add_view(media_type, view_id, view_name, view_type)
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/views.py", line 146, in add_view
                                                tag_id = self.get_tag(view_name)
                                              File "/home/mythtv/.kodi/addons/plugin.video.emby/resources/lib/views.py", line 220, in get_tag
                                                self.kodi_cursor.execute(query, (tag,))
                                            OperationalError: no such table: tag
```

Notice in particular the:

```
16:40:11.997 T:2698992448  NOTICE: EMBY.database -> closing: /home/mythtv/.kodi/userdata/Database/MyVideos107.db - 2846530920
```

But I am not using _sqlite_ here in my installation but rather MySQL and so it's not surprising that that table doesn't exist in that database:

```
# ls -l /home/mythtv/.kodi/userdata/Database/MyVideos107.db
-rw-r--r-- 1 mythtv mythtv 0 Sep 11 16:21 /home/mythtv/.kodi/userdata/Database/MyVideos107.db

```

No tables exist.  None should exist.  Kodi is using MySQL.

**Comment by angelblue05** [comment]
Not really an issue. Emby for Kodi is not compatible with MYSQL. Remove it, and you should be good to go.

**Comment by brianjmurrell** [comment]
Is there any reason it couldn't/shouldn't be?  Are the video and audio libraries the *only* thing in the Kodi database(s)?

**Comment by marcelveldt** [comment]
Emby takes over the need for the centralised DB... Emby IS your centralised database

**Comment by angelblue05** [comment]
Thank you marcel

**Comment by brianjmurrell** [comment]
@marcelveldt I understand how Emby is the centralised source of media.  What I am unclear about is whether the shared database(s) in Kodi are only for media.  I believe they are but wanted to confirm.

**Comment by marcelveldt** [comment]
Kodi has separated databases for each media type. So if you only sync your video content (movies, tv shows, music videos) from Emby to Kodi, you won't use the mysql approach for the videos db. 
It's perfectly fine to centralise databases from Kodi which are not synced with Emby but that's kind of a waste of resources. The whole purpose of having Emby as your backend is that the Kodi client is configured completely standalone (anywhere in the world) "talking" to a centralised Emby server. In that case you can see Kodi as a client for Emby.

**Comment by marcelveldt** [comment]
Besides a database for music and videos, Kodi also has a database for textures and eps data but those can't be moved to mysql.
