### ISSUE TITLE
"local variable 'rating' referenced before assignment" causes library sync thread to crash when syncing music

### ISSUE THREAD

**Issue by petwri** [MediaBrowser/plugin.video.emby#19]
15:01:55 T:140287322093312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'rating' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/main/.kodi/addons/plugin.video.emby/default.py", line 135, in <module>
                                                Main()
                                              File "/home/main/.kodi/addons/plugin.video.emby/default.py", line 102, in __init__
                                                lib.fullSync(manualrun=True)
                                              File "/home/main/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 265, in fullSync
                                                completed = self.music(embycursor, musiccursor, pDialog, compare=manualrun)
                                              File "/home/main/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 976, in music
                                                process[type][1](embyitem)
                                              File "/home/main/.kodi/addons/plugin.video.emby/resources/lib/itemtypes.py", line 1954, in add_updateSong
                                                rating, comment, hasEmbeddedCover = musicutils.getAdditionalSongTags(itemid, rating, API, kodicursor, emby_db, self.enableimportsongrating, self.enableexportsongrating, self.enableupdatesongrating)
                                            UnboundLocalError: local variable 'rating' referenced before assignment
                                            -->End of Python script error report<--

**Comment by angelblue05** [comment]
Thanks for reporting, this is resolved with version 1.1.80.
