### ISSUE TITLE
On stable .strm using emby work on beta no longer

### ISSUE THREAD

**Issue by mcaptur** [MediaBrowser/plugin.video.emby#238]
On stable  .strm files used to work for me - I had to choose play via emby not directly on setting up addon first time - now even though i choose this setting it seams that kodi is playing directly which fails on my streams .. It seams that the option to stream via emby no longer works

2019-04-21 15:18:31.181 T:3420447600 NOTICE: EMBY.helper.playutils -> Skip source selection.
2019-04-21 15:18:31.182 T:3420447600 NOTICE: EMBY.helper.playutils -> --[ direct play ]
2019-04-21 15:18:31.639 T:3412054896 NOTICE: EMBY.monitor -> -->[ q:monitor/Playlist.OnAdd ]
2019-04-21 15:18:31.641 T:3412054896 NOTICE: EMBY.monitor -> {u'item': {u'type': u'episode', u'id': 889}, u'playlistid': 1, 'MonitorMethod': 'Playlist.OnAdd', u'position': 1}
2019-04-21 15:18:31.642 T:3412054896 NOTICE: EMBY.monitor -> --[ playlist ready ]
2019-04-21 15:18:31.692 T:3420447600 NOTICE: EMBY.webservice -> [ playback starting/0 ]
2019-04-21 15:18:31.720 T:3428840304 NOTICE: EMBY.entrypoint.default -> [ playback started ]
2019-04-21 15:18:31.724 T:3428840304 NOTICE: EMBY.default -> ---<[ default ]
2019-04-21 15:18:31.737 T:4090278688 ERROR: Playlist Player: skipping unplayable item: 0, path [http://127.0.0.1:57578/emby/kodi/tvshows/36400/38094/file.strm?KodiId=889&Name=abc.strm&Id=38094]
2019-04-21 15:18:32.058 T:4090278688 NOTICE: VideoPlayer::OpenFile: http://tv.xxx.xxx:80/series/abc/xyz/20560.mkv
2019-04-21 15:18:32.073 T:3428840304 NOTICE: Creating InputStream
2019-04-21 15:18:32.126 T:3624956784 NOTICE: EMBY.player -> [ onPlayBackStarted ]
2019-04-21 15:18:32.129 T:3624956784 NOTICE: EMBY.player -> -->[ play/38094 ] {u'PlaySessionId': u'83c63c4d5ec14056a920fc5d343eee65', 'Muted': False, u'SubtitleStreamIndex': 13, 'Server': <emby.client.EmbyClient object at 0xea5a8d50>, u'MediaSourceId': u'003408390138ff989a2ae9ef00484811', u'AudioStreamIndex': 1, u'CurrentEpisode': {u'rating': 9, u'tvshowid': u'36400', u'episode': 1, u'title': u'Winter', u'season': 1, u'plot': u'plot is this': 2011, u'art': {u'tvshow.fanart': u'http://{emby-server}/emby/Items/36400/Images/Backdrop/0?Format=original&Tag=c974ed8c38b438527b56302dfb5c2715', u'tvshow.poster': u'http://{emby-server}/emby/Items/36400/Images/Primary/0?Format=original&Tag=3863bffebfb852bcb634d08c94c0e506', u'thumb': u'http://{emby-server}/emby/Items/38094/Images/Primary/0?Format=original&Tag=449c3ce1c5a7e47a3cd939cb0a923b85'}, u'playcount': 0, u'showtitle': u'fffff'}, u'ServerId': None, u'Runtime': 37029478400L, u'Type': u'Episode', u'PlayMethod': u'DirectPlay', 'Volume': 75, u'LiveStreamId': None, u'SubsMapping': {}, u'CurrentPosition': 0, 'Track': False, 'Paused': False, u'DeviceId': u'BE20283E8064410EA35128CAA4499EB6', 'File': 'http://tv.xxx.xxx:80/series/abc/xyz/20560.mkv', u'PlayOption': u'Addon', u'Path': u'http://tv.xxx.xxx:80/series/abc/xyz/20560.mkv', u'Id': u'38094'}
2019-04-21 15:18:32.275 T:3624956784 NOTICE: EMBY.monitor -> [ xbmc/Info.OnChanged ]
2019-04-21 15:18:32.283 T:3528995696 NOTICE: EMBY.monitor -> -->[ q:monitor/Player.OnPlay ]
2019-04-21 15:18:32.284 T:3528995696 NOTICE: EMBY.objects.actions -> [ play ] kodi_id: 889 media: episode
2019-04-21 15:18:32.303 T:3428840304 ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2019-04-21 15:18:32.303 T:3428840304 ERROR: CCurlFile::Open failed with code 0 for http://tv.xxx.xxx:80/series/abc/xyz/20560.mkv:
2019-04-21 15:18:32.303 T:3428840304 ERROR: Open - failed to open source http://tv.xxx.xxx:80/series/abc/xyz/20560.mkv
2019-04-21 15:18:32.303 T:3428840304 ERROR: CVideoPlayer::OpenInputStream - error opening [http://tv.xxx.xxx:80/series/abc/xyz/20560.mkv]

**Comment by angelblue05** [comment]
What is the expected behavior? Is the link it's trying to play not correct? You have force http enabled in the add-on settings and it still direct plays?

**Comment by mcaptur** [comment]
Yes i forced http enabled, but it still direct plays.. direct play of my streams does not work via kodi (kodi issue) but it work via emby

**Comment by angelblue05** [comment]
Please provide me with your complete log and not the snippet. Thank you. I will correct your issue for the next beta version, but I'll need your Kodi log to do it.

**Comment by mcaptur** [comment]
find here https://pastebin.com/K9DfSXLr

**Comment by angelblue05** [comment]
Thank you! I should hopefully have a new beta build out tomorrow or at the latest Tuesday.

**Comment by angelblue05** [comment]
Sorry about the delay. While troubleshooting your situation, I found a few other bugs in playback. Thanks for your patience. I'll make a post on the Emby forums when the new build is out.

**Comment by mcaptur** [comment]
no problem. Thanks!

**Comment by angelblue05** [comment]
This is fixed with beta 4.0.15a.

**Comment by mcaptur** [comment]
It doing it again o 4.024a

**Comment by angelblue05** [comment]
Post an updated Kodi log. I’m not seeing issues here.

**Comment by mcaptur** [comment]
2019-05-19 16:43:36.998 T:35772 WARNING: <[ webservice/1585606782536/0 ]
2019-05-19 16:43:37.008 T:35772 WARNING: [ webservice/1585606782536 ] path: /emby/kodi/movies/34380/file.strm?KodiId=364&Name=Bohemian+Rhapsody+%282018%29.strm&Id=34380 params: {'KodiId': '364', 'MediaType': 'movie', 'Name': 'Bohemian Rhapsody (2018).strm', 'Id': '34380'}
2019-05-19 16:43:37.009 T:35772 WARNING: <[ webservice/1585606782536/1 ]
2019-05-19 16:43:37.010 T:45212  NOTICE: EMBY.hooks.webservice -> -->[ queue play ]
2019-05-19 16:43:37.070 T:35772 WARNING: <[ webservice/1585606782536/1 ]
2019-05-19 16:43:37.073 T:35772 WARNING: <[ webservice/1585606782536/0 ]
2019-05-19 16:43:37.083 T:35772 WARNING: <[ webservice/1585606782536/1 ]
2019-05-19 16:43:37.133 T:6608  NOTICE: EMBY.hooks.monitor -> -->[ q:monitor/Playlist.OnAdd ]
2019-05-19 16:43:37.134 T:6608  NOTICE: EMBY.objects.monitor -> {u'item': {u'type': u'movie', u'title': u''}, u'playlistid': 0, 'MonitorMethod': 'Playlist.OnAdd', u'position': 0}
2019-05-19 16:43:37.237 T:24924  NOTICE: EMBY.objects.monitor -> [ xbmc/Playlist.OnRemove ]
2019-05-19 16:43:37.245 T:43160  NOTICE: EMBY.hooks.monitor -> -->[ q:monitor/Playlist.OnAdd ]
2019-05-19 16:43:37.247 T:43160  NOTICE: EMBY.objects.monitor -> [ reset autoplay ]
2019-05-19 16:43:37.249 T:43160  NOTICE: EMBY.objects.monitor -> {u'item': {u'type': u'movie', u'title': u''}, u'playlistid': 0, 'MonitorMethod': 'Playlist.OnAdd', u'position': 0}
2019-05-19 16:43:37.737 T:12932  NOTICE: EMBY.entrypoint.default -> path: ?mode=playstrm&id=34380 params: {
                                                "mode": "playstrm", 
                                                "id": "34380"
                                            }
2019-05-19 16:43:37.805 T:45212  NOTICE: EMBY.objects.play.strm -> --[ play strm ]
2019-05-19 16:43:37.806 T:45212  NOTICE: EMBY.hooks.webservice -> [ relaunch playlist ]
2019-05-19 16:43:37.806 T:45212  NOTICE: EMBY.objects.play.strm -> [ play/34380/0 ]
2019-05-19 16:43:37.816 T:45212  NOTICE: EMBY.objects.play.strm -> [ main/34380/0 ] Bohemian Rhapsody
2019-05-19 16:43:37.856 T:23696  NOTICE: EMBY.hooks.monitor -> -->[ q:monitor/Playlist.OnClear ]
2019-05-19 16:43:37.895 T:45212  NOTICE: EMBY.helper.playutils -> {u'PlaySessionId': u'a750dc28fe29445496291b8ade66a8f3', u'MediaSources': [{u'SupportsDirectStream': True, u'Container': u'mkv', u'RequiresClosing': False, u'DefaultAudioStreamIndex': 1, u'MediaStreams': [{u'IsInterlaced': False, u'Title': u'Bohemian.Rhapsody.2018.1080p.WEB-DL.DD5.1.H264-FGT', u'AverageFrameRate': 23.9760246, u'DisplayLanguage': u'English', u'Width': 1920, u'VideoRange': u'SDR', u'Codec': u'h264', u'IsForced': False, u'AspectRatio': u'2.40:1', u'Type': u'Video', u'IsTextSubtitleStream': False, u'Profile': u'High', u'TimeBase': u'1/1000', u'NalLengthSize': u'4', u'ColorSpace': u'bt709', u'CodecTimeBase': u'1001/48000', u'ColorTransfer': u'bt709', u'RealFrameRate': 23.9760246, u'Language': u'eng', u'Level': 40, u'ColorPrimaries': u'bt709', u'DisplayTitle': u'1080p H264', u'RefFrames': 1, u'BitDepth': 8, u'BitRate': 4925334, u'IsDefault': True, u'IsAnamorphic': False, u'Protocol': u'File', u'Index': 0, u'SupportsExternalStream': False, u'Height': 802, u'IsAVC': True, u'PixelFormat': u'yuv420p', u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'English Dolby Digital 5.1 (Default)', u'ChannelLayout': u'5.1', u'Language': u'eng', u'Title': u'Bohemian.Rhapsody.2018.1080p.WEB-DL.DD5.1.H264-FGT', u'Index': 1, u'Type': u'Audio', u'DisplayLanguage': u'English', u'Level': 0, u'Channels': 6, u'Codec': u'ac3', u'SupportsExternalStream': False, u'CodecTimeBase': u'1/48000', u'Protocol': u'File', u'TimeBase': u'1/1000', u'SampleRate': 48000, u'BitRate': 384000, u'IsTextSubtitleStream': False, u'IsDefault': True, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'English (Default SUBRIP)', u'SupportsExternalStream': True, u'Language': u'eng', u'Index': 2, u'DisplayLanguage': u'English', u'Score': 11221, u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': True, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Spanish (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'spa', u'Index': 3, u'DisplayLanguage': u'Spanish', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'French (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'fre', u'Index': 4, u'DisplayLanguage': u'French', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Croatian (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'hrv', u'Index': 5, u'DisplayLanguage': u'Croatian', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Dutch (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'dut', u'Index': 6, u'DisplayLanguage': u'Dutch', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Polish (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'pol', u'Index': 7, u'DisplayLanguage': u'Polish', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Portuguese (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'por', u'Index': 8, u'DisplayLanguage': u'Portuguese', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Serbian (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'srp', u'Index': 9, u'DisplayLanguage': u'Serbian', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Czech (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'cze', u'Index': 10, u'DisplayLanguage': u'Czech', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Danish (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'dan', u'Index': 11, u'DisplayLanguage': u'Danish', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Italian (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'ita', u'Index': 12, u'DisplayLanguage': u'Italian', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Hungarian (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'hun', u'Index': 13, u'DisplayLanguage': u'Hungarian', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Romanian (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'rum', u'Index': 14, u'DisplayLanguage': u'Romanian', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Turkish (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'tur', u'Index': 15, u'DisplayLanguage': u'Turkish', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsForced': False, u'IsInterlaced': False, u'DisplayTitle': u'Arabic (SUBRIP)', u'SupportsExternalStream': True, u'Language': u'ara', u'Index': 16, u'DisplayLanguage': u'Arabic', u'DeliveryMethod': u'Embed', u'Codec': u'subrip', u'CodecTimeBase': u'0/1', u'Protocol': u'File', u'TimeBase': u'1/1000', u'Level': 0, u'Type': u'Subtitle', u'IsTextSubtitleStream': True, u'IsDefault': False, u'IsExternal': False}, {u'IsInterlaced': False, u'Index': 17, u'Width': 120, u'Codec': u'mjpeg', u'IsForced': False, u'Type': u'EmbeddedImage', u'IsTextSubtitleStream': False, u'Profile': u'192', u'BitDepth': 8, u'SupportsExternalStream': False, u'ColorSpace': u'bt470bg', u'CodecTimeBase': u'0/1', u'RealFrameRate': 90000, u'Level': -99, u'RefFrames': 1, u'TimeBase': u'1/90000', u'IsDefault': False, u'IsAnamorphic': False, u'Protocol': u'File', u'Height': 176, u'PixelFormat': u'yuvj444p', u'IsExternal': False}, {u'IsInterlaced': False, u'Index': 18, u'Width': 213, u'Codec': u'mjpeg', u'IsForced': False, u'AspectRatio': u'16:9', u'Type': u'EmbeddedImage', u'IsTextSubtitleStream': False, u'Profile': u'192', u'BitDepth': 8, u'SupportsExternalStream': False, u'ColorSpace': u'bt470bg', u'CodecTimeBase': u'0/1', u'RealFrameRate': 90000, u'Level': -99, u'RefFrames': 1, u'TimeBase': u'1/90000', u'IsDefault': False, u'IsAnamorphic': False, u'Protocol': u'File', u'Height': 120, u'PixelFormat': u'yuvj444p', u'IsExternal': False}, {u'IsInterlaced': False, u'Index': 19, u'Width': 600, u'Codec': u'mjpeg', u'IsForced': False, u'Type': u'EmbeddedImage', u'IsTextSubtitleStream': False, u'Profile': u'192', u'BitDepth': 8, u'SupportsExternalStream': False, u'ColorSpace': u'bt470bg', u'CodecTimeBase': u'0/1', u'RealFrameRate': 90000, u'Level': -99, u'RefFrames': 1, u'TimeBase': u'1/90000', u'IsDefault': False, u'IsAnamorphic': False, u'Protocol': u'File', u'Height': 882, u'PixelFormat': u'yuvj444p', u'IsExternal': False}, {u'IsInterlaced': False, u'Index': 20, u'Width': 1067, u'Codec': u'mjpeg', u'IsForced': False, u'AspectRatio': u'16:9', u'Type': u'EmbeddedImage', u'IsTextSubtitleStream': False, u'Profile': u'192', u'BitDepth': 8, u'SupportsExternalStream': False, u'ColorSpace': u'bt470bg', u'CodecTimeBase': u'0/1', u'RealFrameRate': 90000, u'Level': -99, u'RefFrames': 1, u'TimeBase': u'1/90000', u'IsDefault': False, u'IsAnamorphic': False, u'Protocol': u'File', u'Height': 600, u'PixelFormat': u'yuvj444p', u'IsExternal': False}], u'Type': u'Default', u'ReadAtNativeFramerate': False, u'RequiresLooping': False, u'Path': u'http://tv.avc.uno:80/movie/6asdhvsadf80/vrasdg053/25733.mkv', u'RequiresOpening': False, u'Bitrate': 4925334, u'IsRemote': True, u'Name': u'Bohemian Rhapsody (2018)', u'RequiredHttpHeaders': {}, u'SupportsTranscoding': True, u'SupportsDirectPlay': True, u'Formats': [], u'Protocol': u'Http', u'IsInfiniteStream': False, u'RunTimeTicks': 81193590000L, u'DefaultSubtitleStreamIndex': 2, u'SupportsProbing': False, u'Id': u'29db4cfdff91f5929f88d99fd7d1169a', u'Size': 4998819603L}]}
2019-05-19 16:43:37.896 T:45212  NOTICE: EMBY.helper.playutils -> Skip source selection.
2019-05-19 16:43:37.896 T:45212  NOTICE: EMBY.helper.playutils -> --[ direct play ]
2019-05-19 16:43:37.908 T:45212  NOTICE: EMBY.hooks.webservice -> ERROR:: 'module' object has no attribute 'default_settings_default'
                                            Traceback (most recent call last):
                                              File "C:\Users\mark\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\hooks\webservice.py", line 372, in run
                                                position = play.play(position)
                                              File "C:\Users\mark\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.emby\emby\objects\play\strm.py", line 92, in play
                                                self._set_playlist(listitem)
                                              File "C:\Users\mark\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.emby\emby\objects\play\strm.py", line 148, in _set_playlist
                                                play.set_subtitles_in_database(source, self.info['Item']['PlaybackInfo'].get('Subtitles', {}))
                                              File "C:\Users\mark\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\helper\playutils.py", line 673, in set_subtitles_in_database
                                                default = objects.utils.default_settings_default()
                                            AttributeError: 'module' object has no attribute 'default_settings_default'
2019-05-19 16:43:37.915 T:45212  NOTICE: EMBY.hooks.webservice -> --<[ queue play ]
2019-05-19 16:43:37.956 T:12932  NOTICE: EMBY.entrypoint.default -> [ playback aborted ]
2019-05-19 16:43:37.956 T:12932  NOTICE: EMBY.default -> ---<[ default ]
2019-05-19 16:43:38.029 T:22660   ERROR: Playlist Player: skipping unplayable item: 0, path [http://127.0.0.1:57578/emby/kodi/movies/34380/file.strm?KodiId=364&Name=Bohemian+Rhapsody+%282018%29.strm&Id=34380]
2019-05-19 16:43:38.029 T:22660 WARNING: Attempt to set unplayable index 0

**Comment by mcaptur** [comment]
Force http playback is selected
