### ISSUE TITLE
Readtimeout on Kodi resync

### ISSUE THREAD

**Issue by mammo0** [MediaBrowser/plugin.video.emby#305]
Hello,

I'm using Emby since a few weeks now together with the Kodi plugin. At first everything went alright: The initial sync of my Emby library and later the resyncs after Kodi starts again.

But since last sunday I'm experienced a Readtimeout error when I'm starting Kodi. I must say that between the last resync between Kodi and Emby there was more than a week. And I've got a quite big media library that gets updated every day via a scheduled task in Emby. Especially some tvshows get an update of one or more episodes a day.

At first a workaround was to increase the value of `DEFAULT_HTTP_TIMEOUT` in `plugin.video.emby/libraries/emby/core/configuration.py`. Because the response of the Emby server took more than 30 seconds.

But today I started the Kodi resync process on a second machine and the resync took more than 5 minutes! After that time I had to kill the Emby server process since it used more than 1,5GB of RAM at that time and my server has only 2GB.
I've also looked at the Emby server log, but there aren't any errors or warnings. I don't think that there are so much changes to my Emby library in two weeks that a resync will take this much time. So maybe it is rather a bug at server side rather than in the kodi plugin?

Thank you for your help in advance!

A part of the Kodi log on my second machine from today (the same error/behaviour occurs also with the Kodi plugin version 4.1.14):

```
[... Kodi startup (no Errors logged here) ...]
2019-08-24 11:50:06.490 T:8200  NOTICE: EMBY.patch -> --->[ patch ]
2019-08-24 11:50:06.490 T:9740  NOTICE: EMBY.hooks.webservice -> --->[ webservice/57578 ]
2019-08-24 11:50:06.490 T:8200  NOTICE: EMBY.patch -> --[ check updates/181167256 ]
2019-08-24 11:50:08.173 T:8200  NOTICE: EMBY.patch -> <[ patch min not met: 4.1.13 ]
2019-08-24 11:50:08.173 T:8200  NOTICE: EMBY.patch -> --[ check updates/181167256 ]
2019-08-24 11:50:08.251 T:8200  NOTICE: EMBY.helper.utils -> DELETE C:\Users\<user>\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.emby\emby
2019-08-24 11:50:08.251 T:8200  NOTICE: EMBY.patch -> From https://github.com/MediaBrowser/plugin.video.emby.objects/archive/181167257.zip to C:\Users\<user>\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.emby\emby\181167257.zip
2019-08-24 11:50:10.554 T:8200  NOTICE: EMBY.helper.utils -> Unzipped C%3A%5CUsers%5C<user>%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data%5Cplugin.video.emby%5Cemby%5C181167257.zip
2019-08-24 11:50:10.779 T:8200  NOTICE: EMBY.patch -> ---[ objects reloaded ]
2019-08-24 11:50:10.781 T:8200  NOTICE: EMBY.patch -> --<[ new objects/181167257 ]
2019-08-24 11:50:11.035 T:8200  NOTICE: EMBY.service -> -->[ service ]
2019-08-24 11:50:11.038 T:8200  NOTICE: EMBY.service -> Delay startup by 0 seconds.
2019-08-24 11:50:11.246 T:6900  NOTICE: EMBY.entrypoint.service -> --->>>[ EMBY ]
2019-08-24 11:50:11.246 T:6900  NOTICE: EMBY.entrypoint.service -> Version: 4.1.12
2019-08-24 11:50:11.247 T:6900  NOTICE: EMBY.entrypoint.service -> KODI Version: 18.3 Git:20190619-89472b7d69
2019-08-24 11:50:11.257 T:6900  NOTICE: EMBY.entrypoint.service -> Platform: Windows
2019-08-24 11:50:11.272 T:6900  NOTICE: EMBY.entrypoint.service -> OS: Kodi/8072MB
2019-08-24 11:50:11.272 T:6900  NOTICE: EMBY.entrypoint.service -> Python Version: 2.7.13 (default, Jul 14 2017, 17:41:26) [MSC v.1900 64 bit (AMD64)]
2019-08-24 11:50:11.285 T:6900  NOTICE: EMBY.entrypoint.service -> Using dynamic paths: True
2019-08-24 11:50:11.286 T:6900  NOTICE: EMBY.entrypoint.service -> Log Level: 1
2019-08-24 11:50:11.291 T:6900  NOTICE: EMBY.entrypoint.service -> ---[ db/None ]
2019-08-24 11:50:11.413 T:6900  NOTICE: Emby -> ---[ START EMBYCLIENT ]---
2019-08-24 11:50:11.588 T:6900  NOTICE: EMBY.views -> Unable to retrieve libraries: NotConnected
2019-08-24 11:50:11.630 T:6900  NOTICE: EMBY.client -> DeviceId loaded: 7436E2BEA57E497AA2596CE1085C6E61
2019-08-24 11:50:11.640 T:11144  NOTICE: EMBY.hooks.monitor -> --->[ listener ]
2019-08-24 11:50:11.656 T:4892  NOTICE: Emby -> ---[ STOPPED EMBYCLIENT: default ]---
2019-08-24 11:50:11.656 T:4892  NOTICE: EMBY.connect -> --[ server/default ]
2019-08-24 11:50:11.672 T:4892  NOTICE: Emby -> ---[ START EMBYCLIENT ]---
2019-08-24 11:50:11.680 T:4892  NOTICE: Emby.emby.core.connection_manager -> Begin connect
2019-08-24 11:50:12.685 T:4892  NOTICE: Emby.emby.core.connection_manager -> Found Servers: []
2019-08-24 11:50:12.692 T:4892  NOTICE: Emby.emby.core.connection_manager -> Begin connectToServers, with 1 servers
2019-08-24 11:50:12.697 T:4892  NOTICE: Emby.emby.core.connection_manager -> testing connection mode 2 with server emby
2019-08-24 11:50:12.698 T:4892  NOTICE: Emby.emby.core.connection_manager -> tryConnect url: https://{emby-server}/emby/system/info/public
2019-08-24 11:50:13.548 T:4892  NOTICE: Emby.emby.core.connection_manager -> calling onSuccessfulConnection with connection mode 2 with server emby
2019-08-24 11:50:14.045 T:4892  NOTICE: Emby.emby.client -> User is authenticated.
2019-08-24 11:50:15.778 T:3180  NOTICE: EMBY.hooks.monitor -> -->[ q:monitor/LoadServer ]
2019-08-24 11:50:15.808 T:3180  NOTICE: EMBY.hooks.monitor -> --[ post capabilities/1592601c27f5460b99ee9778982da08a ]
2019-08-24 11:50:15.812 T:11100  NOTICE: Emby.emby.core.ws_client -> Websocket url: wss://{emby-server}/embywebsocket?api_key={emby-token}&device_id=7436E2BEA57E497AA2596CE1085C6E61
2019-08-24 11:50:15.814 T:4892  NOTICE: EMBY.setup -> ---<[ setup ]
2019-08-24 11:50:16.162 T:11100  NOTICE: Emby.emby.core.ws_client -> --->[ websocket ]
2019-08-24 11:50:16.314 T:6900  NOTICE: EMBY.entrypoint.service -> [ onNotification/plugin.video.emby/ServerOnline ]
2019-08-24 11:50:16.446 T:7296  NOTICE: EMBY.library -> --->[ library ]
2019-08-24 11:50:17.730 T:7296  NOTICE: EMBY.database -> [emby] 1 rows updated.
2019-08-24 11:50:19.067 T:7296  NOTICE: Previous line repeats 2 times.
2019-08-24 11:50:19.067 T:7296  NOTICE: EMBY.library -> --[ retrieve changes ] 2019-08-09T20:19:30z
[... Some more Kodi log here (no errors) ...]
2019-08-24 11:53:01.276 T:7296  NOTICE: Emby.emby.core.http -> ERROR:: HTTPSConnectionPool(host='ext.ammon.ftp.sh', port=443): Read timed out. (read timeout=30)
2019-08-24 11:53:01.279 T:7296  NOTICE: EMBY.library -> ERROR:: 
                                            Traceback (most recent call last):
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\library.py", line 490, in startup
                                                self.get_fast_sync()
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\library.py", line 539, in get_fast_sync
                                                self.fast_sync(enable_fast_sync)
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\resources\lib\library.py", line 563, in fast_sync
                                                data = self.server['api'].get_date_modified(last_sync, library.replace('Mixed:', ""), "Series,Episode,BoxSet,Movie,MusicVideo,MusicArtist,MusicAlbum,Audio")
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\libraries\emby\core\api.py", line 285, in get_date_modified
                                                'Fields': info()
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\libraries\emby\core\api.py", line 86, in users
                                                return  self._get("Users/{UserId}%s" % handler, params)
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\libraries\emby\core\api.py", line 53, in _get
                                                return  self._http("GET", handler, {'params': params})
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\libraries\emby\core\api.py", line 50, in _http
                                                return  self.client.request(request)
                                              File "C:\Users\<user>\AppData\Roaming\Kodi\addons\plugin.video.emby\libraries\emby\core\http.py", line 129, in request
                                                raise HTTPException("ReadTimeout", error)
                                            HTTPException
2019-08-24 11:53:03.282 T:7296  NOTICE: EMBY.library -> ---<[ library ]
2019-08-24 11:53:58.645 T:6900  NOTICE: EMBY.objects.monitor -> [ xbmc/GUI.OnScreensaverActivated ]
2019-08-24 11:53:59.345 T:6900  NOTICE: EMBY.objects.monitor -> [ xbmc/GUI.OnScreensaverDeactivated ]
```

**Comment by angelblue05** [comment]
Do you have music in your server and Is it being updated?

**Comment by mammo0** [comment]
No I've got no music in my library. Just movies and TV shows.
And the AutoBoxSet-Addon is running.

**Comment by angelblue05** [comment]
Ok I will see what can be done. If you increase the timeout value to some ridiculous number it always works? Do you know how many items it’s trying to pull from your server?

**Comment by mammo0** [comment]
On the last sunday as I first noticed the issue, it helped to set the timeout to 120 seconds.

In the logs I saw, that the client did always only one pull from the server. On server side it took about 90 seconds to perform the request and send the answer to my client. The request from the client was always answered. But the client aborted the connection after the 30 seconds timeout. Only after I set the timeout to 120 seconds, the response from the server was accepted and processed by the client.

But today I had the problem that it didn't helped to increase the timeout value, because the Emby server process took to much RAM before it could complete the client request. I had to kill the process after about 5 minutes. But until I killed the server process there were no errors or warnings in the Emby server log file.

**Comment by mammo0** [comment]
The answer I got on sunday from the server after I increased the timeout included many changes. I wondered were all these changes came from, since there weren't many changes in my media library. Just about 5 - 10 new movies and about 20 - 50 new episodes.

**Comment by angelblue05** [comment]
For now, what you can do to move forward is ignore the failure and launch emby for kodi > open the context menu on the emby library entry > update library.

I will have to check with Luke to see if it’s possible to pull that info by chunks rather than one call. I’ll keep you posted.

**Comment by mammo0** [comment]
Thanks for your reply. I will do it as you suggested for now.

And I also think that pulling in parts is better than as a whole. Maybe you could link that to the value of requests that are made during a normal/initial sync of the Emby library (I think the default value is 15 now).

**Comment by angelblue05** [comment]
4.1.15 include your changes.
