### ISSUE TITLE
Sync the playlist / nodes refresh failed

### ISSUE THREAD

**Issue by cmoulliard** [MediaBrowser/plugin.video.emby#36]
I have installed the Kodi Embed Plugin (2.1.0) on Kodi (Feb 2015) but when I try to sync the playlist / nodes to my server (192.168.1.80:8096) I get a "refresh failed error". What could be the issue ?
I can access to the Emby UpnP server from my kodi / raspberry machine and watch movies ....
 
Kodi Version : Feb 2015
Raspbian Gnu/Linux 7 (wheezy) Linux Kernel 3.12.31

REMARK : I have installed the latest version of KODI (= OSMC - Version 2016-04-01) and I get also the same problem

Here is the info reported within the kodi.log file 
 
```
19:17:24 2187.001709 T:2829054960  NOTICE: EMBY Service -> ======== START EMBY ========
19:17:24 2187.012207 T:2829054960  NOTICE: EMBY Service -> Platform: Linux/RPi
19:17:24 2187.013184 T:2829054960  NOTICE: EMBY Service -> KODI Version: 16.1-RC3
19:17:24 2187.041016 T:2829054960  NOTICE: EMBY Service -> EMBY Version: 2.2.10
19:17:24 2187.092041 T:2829054960  NOTICE: EMBY Service -> Using plugin paths: True
19:17:24 2187.093018 T:2829054960  NOTICE: EMBY Service -> Log Level: 1
19:17:24 2187.109131 T:2829054960  NOTICE: EMBY VideoNodes -> Clearing nodes properties.
19:17:24 2187.539307 T:2829054960  NOTICE: EMBY ClientInfo -> DeviceId loaded: 49996B559B3942B981244A416BBC914D
19:17:27 2190.468506 T:2829054960  NOTICE: EMBY Service -> Server is online and ready.
19:17:27 2190.491455 T:2694837232  NOTICE: EMBY UserClient -> ----===## Starting UserClient ##===----
19:17:28 2190.686768 T:2694837232  NOTICE: EMBY UserClient -> Missing server information.
19:17:28 2191.492188 T:2829054960  NOTICE: EMBY Service -> Not authenticated yet.
20:20:40 5982.640625 T:2638210032  NOTICE: EMBY DownloadUtils -> Unknown error connecting to: /emby/Users//Views?format=json
20:20:40 5982.642578 T:2638210032  NOTICE: EMBY DownloadUtils -> Invalid URL '/emby/Users//Views?format=json': No schema supplied. Perhaps you meant http:///emby/Users//Views?format=json?
20:20:40 5982.645020 T:2638210032  NOTICE: EMBY -> Refresh playlists/nodes failed: string indices must be integers, not str
20:21:36 6038.632324 T:2638210032  NOTICE: EMBY -> Reset login attempts.
22:50:13 14955.798828 T:2829054960  NOTICE: EMBY Player -> Could not find itemId, cancelling playback report...
22:50:19 14962.112305 T:2829054960  NOTICE: EMBY Player -> Clear playlist properties.
````

 Request : http://192.168.1.80:8096/mediabrowser/Users/Public?format=json

````
[{"Name":"dabou","ServerId":"83834b2e7d734ae6868c46c43ec237bb","Id":"a0d74638adb348a98ac4d92038863ca7","HasPassword":false,"HasConfiguredPassword":false,"HasConfiguredEasyPassword":false,"LastLoginDate":"2016-05-01T18:47:53.1090190Z","LastActivityDate":"2016-05-01T20:51:29.1686390Z","Configuration":{"PlayDefaultAudioTrack":true,"DisplayMissingEpisodes":false,"DisplayUnairedEpisodes":false,"GroupMoviesIntoBoxSets":false,"GroupedFolders":[],"SubtitleMode":"Default","DisplayCollectionsView":false,"DisplayFoldersView":false,"EnableLocalPassword":false,"OrderedViews":["1adb21f211b28ad385581304449a107e","52f1cc5cfe5ba8c9452cebe7bca9e026"],"IncludeTrailersInSuggestions":true,"LatestItemsExcludes":[],"PlainFolderViews":[],"HidePlayedInLatest":true,"DisplayChannelsInline":true,"RememberAudioSelections":true,"RememberSubtitleSelections":true,"EnableNextEpisodeAutoPlay":true},"Policy":{"IsAdministrator":true,"IsHidden":false,"IsDisabled":false,"BlockedTags":[],"EnableUserPreferenceAccess":true,"AccessSchedules":[],"BlockUnratedItems":[],"EnableRemoteControlOfOtherUsers":true,"EnableSharedDeviceControl":true,"EnableLiveTvManagement":true,"EnableLiveTvAccess":true,"EnableMediaPlayback":true,"EnableAudioPlaybackTranscoding":true,"EnableVideoPlaybackTranscoding":true,"EnableContentDeletion":true,"EnableContentDownloading":true,"EnableSync":true,"EnableSyncTranscoding":true,"EnabledDevices":[],"EnableAllDevices":true,"EnabledChannels":[],"EnableAllChannels":true,"EnabledFolders":[],"EnableAllFolders":true,"InvalidLoginAttemptCount":0,"EnablePublicSharing":true}}]
````

I can't also sync manually

```
08:36:42 3744.797607 T:2709226480  NOTICE: Using Image Cache Thread Count: 0 -> 1
08:36:42 3744.806885 T:2709226480  NOTICE: plugin.video.emby started
08:36:42 3744.807617 T:2709226480  NOTICE: Parameter string: ?mode=manualsync
08:36:42 3744.862549 T:2709226480  NOTICE: EMBY -> Toggling screensaver:  {"id":0,"jsonrpc":"2.0","result":true}
08:36:51 3753.649170 T:2709226480  NOTICE: Using Image Cache Thread Count: 0 -> 1
08:36:51 3753.974854 T:2709226480  NOTICE: EMBY DownloadUtils -> Unknown error connecting to: /emby/Users//Views?format=json
08:36:51 3753.975586 T:2709226480  NOTICE: EMBY DownloadUtils -> Invalid URL '/emby/Users//Views?format=json': No schema supplied. Perhaps you meant http:///emby/Users//Views?format=json?
08:36:51 3754.026123 T:2709226480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.emby/default.py", line 151, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/plugin.video.emby/default.py", line 118, in __init__
                                                librarysync.ManualSync().sync(dialog=True)
                                              File "/home/osmc/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 1078, in sync
                                                return self.fullSync(manualrun=True, forceddialog=dialog)
                                              File "/home/osmc/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 270, in fullSync
                                                self.maintainViews(embycursor, kodicursor)
                                              File "/home/osmc/.kodi/addons/plugin.video.emby/resources/lib/librarysync.py", line 383, in maintainViews
                                                grouped_views = result['Items']
                                            TypeError: string indices must be integers, not str
                                            -->End of Python script error report<--
08:36:52 3754.677246 T:2709226480 WARNING: CPythonInvoker(4, /home/osmc/.kodi/addons/plugin.video.emby/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.emby/default.py" has lef
t several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCA
ddon9xbmcaddon5AddonE
08:36:52 3754.691162 T:3024024496   ERROR: GetDirectory - Error getting plugin://plugin.video.emby/?mode=manualsync
08:36:52 3754.701904 T:3024024496   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.emby/?mode=manualsync) failed
08:37:32 3795.149414 T:2735731696  NOTICE: ES: Client  from 192.168.1.5 timed out
```

**Comment by cmoulliard** [comment]
I can reproduce the error if I install the kodi emby addon top of Kodi application installed on MacOS X

**Comment by cmoulliard** [comment]
I have installed this plugin on Emby Server (running on MacOS X - Version 3.0.5933.0) --> Emby.Kodi Sync Queue - 1.0.5947.38121

**Comment by angelblue05** [comment]
Do you have your server address entered in the emby for kodi add-on config? It's complaining there is none. That's why it's failing right now.

**Comment by cmoulliard** [comment]
Problem resolved after changing the IP address of the Emby Server
