### ISSUE TITLE
Next Episodes does not work in Kodi 18.X

### ISSUE THREAD

**Issue by jwor80** [MediaBrowser/plugin.video.emby#403]
If I go into the emby-next-gen 5.3.2 add-on > Browse to a Emby TV Show list > Click Next Episodes kodi 18.9 locks up. This appears to be an issue on RPi & Windows.  When I test with Kodi 19 I do not see any issues and the Next Episodes list is populated.

2021-12-20 12:58:03.814 T:16672   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2021-12-20 13:01:27.489 T:13648   ERROR: Exception in thread Thread-21:
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.emby-next-gen\hooks\monitor.py", line 795, in run
                                                self.monitor.Menu.get_next_episodes(self.data['Handle'], self.data['libraryname'])
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.emby-next-gen\helper\pluginmenu.py", line 457, in get_next_episodes
                                                episodes = result['result']['episodes']
                                            KeyError: 'episodes'

**Comment by quickmic** [comment]
Can you please perform a test with beta version? A complete database resync is mandatory 5.x -> 6.x
Probably you should take a full Kodi backup.

**Comment by quickmic** [comment]
Exactly the same issue?
get_next_episodes
episodes = result['result']['episodes']
KeyError: 'episodes'

I can write a workaround, but no sure what's the actual cause.
I also release 6.2.5 beta today, but I assume it will not fix the issue. Anyway, please try again. If it's still not fixed, I'll add the workaround.

**Comment by quickmic** [comment]
If 6.2.5 doesn't fix the problem, please try:
https://codeload.github.com/quickmic/plugin.video.emby/zip/refs/heads/next-gen-dev

**Comment by jwor80** [comment]
I test with 6.2.5 and it did not resolve the issue.  However I installed the add-on from the link above and the next episode list worked perfectly!  Thank you!

**Comment by quickmic** [comment]
Great, this fix will be added in next version.

**Comment by jwor80** [comment]
@quickmic The Next Episode is still working, but do you have any thoughts on why it may be so slow to load? Prior to the fix I used the embycon addon to pull the next episodes as a work around it will would take a couple of seconds to load. With the emby-next-gen addon fixed it takes 10-15 seconds to load.
